name: fim
description: A new Flutter IM application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  grpc: ^2.8.0
  protobuf: ^1.0.1

  device_info: 0.4.0+2
  fluttertoast: ^3.0.3
  sqflite: ^1.3.0
  path:
  flutter_local_notifications: ^3.0.1+4
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  dio: ^3.0.10
  provider: ^4.3.2+3
  cached_network_image: ^2.5.0
  photo_view: ^0.10.3
  logger: ^0.9.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.12+4

  grpc: ^2.8.0
  protobuf: ^1.0.1

  device_info: 0.4.0+2
  fluttertoast: ^3.0.3
  sqflite: ^1.3.0
  path:

  flutter_local_notifications: ^3.0.1+4
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  dio: ^3.0.10
  provider: ^4.3.2+3
  cached_network_image: ^2.5.0
  photo_view: ^0.10.3
  logger: ^0.9.4


flutter:
  uses-material-design: true

  assets:
    - assets/

